script:
  # after successful tests, publish binaries if specified in commit message
  - ./scripts/publish.sh --toolset=${TOOLSET:-} --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")

# the matrix allows you to specify different operating systems and environments to
# run your tests and build binaries
matrix:
  include:

    ## ** Builds that are published **

    # linux cfi build node release
    - os: linux
      env: BUILDTYPE=release TOOLSET=cfi CXXFLAGS="-fsanitize=cfi -fvisibility=hidden" LDFLAGS="-fsanitize=cfi"
    # linux publishable node release
    - os: linux
      env: BUILDTYPE=release
    # linux publishable node release
    - os: linux
      env: BUILDTYPE=debug
    # osx publishable node release
    - os: osx
      osx_image: xcode11
      env: BUILDTYPE=release
    # osx publishable node release
    - os: osx
      osx_image: xcode11
      env: BUILDTYPE=debug
    # linux sanitizer build node debug
    - os: linux
      env: BUILDTYPE=debug TOOLSET=asan
      sudo: required
      # Overrides `install` to set up custom asan flags
      install:
        - make sanitize
      # Overrides `before_script` (tests are already run in `make sanitize`)
      before_script: true