name: tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        build-type: ['release', 'debug']
        node-version: ['16']

    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt-get install -y gcc-6 g++-6 libstdc++-6-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and setup
        run: |
          node -v
          which node
          clang++ -v
          which clang++
          make "${{ matrix.build-type }}"

      - name: Run tests
        run: |
          npm test